echo ""
echo " , _                          , _     , _                    "
echo "/|/ \|     _ |\    (|  |  |_//|/ \   /|/ \|\        _, o     "
echo " |__/|/\  |/ |/     |  |  |   |__/    |__/|/ |  |  / | | /|/|"
echo " |   |  |/|_/|_/     \/ \/    |       |   |_/ \/|_/\/|/|/ | |_/"
echo "                                                    (|"
echo ""
echo "Setup completed! Login to the site at http://localhost:8081/wp-admin/"
echo ""
echo "Username: admin"
echo "Password: password"
echo ""
echo "Phel admin widget should be visible on the dashboard..."
